# Generated by Django 4.1.5 on 2023-05-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Categories/photos/Image/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Employee_WEB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/Service/photos/Image/%Y/%m/%d/')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Services', to='webs.categories')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webs.web'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webs.service')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webs.web')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('knew_from', models.CharField(choices=[('كيف عرفتنا', 'كيف عرفتنا'), ('تأمين', 'تأمين'), ('صديق ', 'صديق '), ('أسرة', 'أسرة'), ('الجيران', 'الجيران'), ('جوجل ', 'جوجل '), ('واتساب', 'واتساب'), ('سناب', 'سناب'), ('انستقرام', 'انستقرام'), ('تويتر', 'تويتر'), ('فيس بوك ', 'فيس بوك '), ('تيك توك', 'تيك توك'), ('يوتيوب ', 'يوتيوب '), ('البريد الإلكتروني', 'البريد الإلكتروني'), ('موقع', ' موقع الإلكتروني'), ('آخر', 'آخر')], max_length=50)),
                ('service', models.ManyToManyField(blank=True, to='webs.service')),
                ('web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webs.web')),
            ],
        ),
    ]
