# Generated by Django 4.1.5 on 2023-05-16 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='Employee_WEB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Users.employee'),
        ),
    ]
