# Generated by Django 4.1.5 on 2023-05-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_alter_web_employee_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='web',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webs.web'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Services', to='webs.categories'),
        ),
    ]
