# Generated by Django 4.1.5 on 2023-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0003_alter_categories_web_alter_service_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status_appointment',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('inquiries', 'الاستفسار'), ('unconfirmed', 'حجز غير مؤكد'), ('cancel', 'إلغاءحجزه'), ('notanswering', 'عدم الرد'), ('confirmed', 'حجز مؤكد'), ('missed_reservation', 'حجز فائت'), ('visit', 'حضر'), ('waiting_list', 'قائمة الانتظارت'), ('Service_done', 'تم تقديم الخدمة')], default='انتظار', max_length=30),
        ),
    ]
