# Generated by Django 4.1.5 on 2023-05-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0004_booking_status_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Appointment',
        ),
    ]
