# Generated by Django 4.1.5 on 2023-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0005_rename_booking_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_appointment',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('inquiries', 'الاستفسار'), ('cancel', 'إلغاءحجزه'), ('notanswering', 'عدم الرد'), ('confirmed', 'حجز مؤكد'), ('visit', 'حضر')], default='انتظار', max_length=30),
        ),
    ]
