# Generated by Django 4.1.5 on 2023-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0006_alter_appointment_status_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='long_image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Service/photos/Image/long/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Service/photos/Image/Service/%Y/%m/%d/'),
        ),
    ]
