# Generated by Django 4.1.5 on 2023-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0007_service_long_image_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='FaviconIco',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/photos/FaviconIco/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='web',
            name='Map_Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='OpeningHours',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='PHONE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Title_logo',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/photos/logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='web',
            name='Twitterlinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Whatsapp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='authorLinke',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='facebooklinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='instagramlinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='linkedinlinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/photos/logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='web',
            name='silderImage',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/photos/silderImage/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='web',
            name='snapchat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
