# Generated by Django 4.1.5 on 2023-05-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0008_web_address_web_description_web_faviconico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('WEBQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qestions', to='webs.web')),
            ],
        ),
    ]
