# Generated by Django 4.1.5 on 2023-05-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0009_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='files/images/WEB/Image/photos/Image/%Y/%m/%d/')),
                ('imagename', models.CharField(blank=True, max_length=300, null=True)),
                ('WEBQImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='webs.web')),
            ],
        ),
    ]
