# Generated by Django 4.1.5 on 2023-05-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0012_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('Image', models.FileField(blank=True, null=True, upload_to='files/images/WEB/Doctors/photos/%Y/%m/%d/')),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('WEBQSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='webs.web')),
            ],
        ),
    ]
