# Generated by Django 4.1.5 on 2023-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0013_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
