# Generated by Django 4.1.5 on 2023-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0014_appointment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='knew_from',
            field=models.CharField(blank=True, choices=[('كيف عرفتنا', 'كيف عرفتنا'), ('تأمين', 'تأمين'), ('صديق ', 'صديق '), ('أسرة', 'أسرة'), ('الجيران', 'الجيران'), ('جوجل ', 'جوجل '), ('واتساب', 'واتساب'), ('سناب', 'سناب'), ('انستقرام', 'انستقرام'), ('تويتر', 'تويتر'), ('فيس بوك ', 'فيس بوك '), ('تيك توك', 'تيك توك'), ('يوتيوب ', 'يوتيوب '), ('البريد الإلكتروني', 'البريد الإلكتروني'), ('موقع', ' موقع الإلكتروني'), ('آخر', 'آخر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
