# Generated by Django 4.1.5 on 2023-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0015_alter_appointment_knew_from_alter_appointment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
