# Generated by Django 4.1.5 on 2023-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0016_categories_views_service_views_web_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
