# Generated by Django 4.1.5 on 2023-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0017_alter_categories_views_alter_service_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Click_booking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Click_whatsapp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Click_booking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Click_whatsapp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='views_Categories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
