# Generated by Django 4.1.5 on 2023-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0018_service_click_booking_service_click_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='views_checkout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='views_confirmation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
