# Generated by Django 4.1.5 on 2023-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0019_web_views_checkout_web_views_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Click_whatsapp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Click_whatsapp_Categories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
