# Generated by Django 4.1.5 on 2023-05-27 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0020_categories_click_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
