# Generated by Django 4.1.5 on 2023-05-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0021_web_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Categories/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Doctors/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Service/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='long_image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Service/long/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='web',
            name='FaviconIco',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/FaviconIco/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='web',
            name='Title_logo',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Title_logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='web',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='web',
            name='silderImage',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/silderImage/%Y/%m/%d/'),
        ),
    ]
