# Generated by Django 4.1.5 on 2023-05-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0022_alter_categories_image_alter_doctors_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='WEBQSection',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='WEBQImage',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='WEBQInsurance',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='WEBQuestions',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='WEBQSection',
            new_name='web',
        ),
    ]
