# Generated by Django 4.1.5 on 2023-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0023_rename_webqsection_doctors_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='pixal_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
