# Generated by Django 4.1.5 on 2023-05-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0024_web_pixal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/WEB/Section/%Y/%m/%d/'),
        ),
    ]
