# Generated by Django 4.1.5 on 2023-05-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0026_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='active',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='active',
        ),
        migrations.RemoveField(
            model_name='section',
            name='active',
        ),
    ]
