# Generated by Django 4.1.5 on 2023-05-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0027_remove_categories_active_remove_doctors_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='authorLinke',
        ),
    ]
